using System.Runtime.InteropServices;
using NAudio.Wave.SampleProviders;
using SDL3;

namespace RayBlast;

internal static class SDLExtensionMethods {
    internal static SDL.FColor ToSDL(this ColorF colorF) {
        return new SDL.FColor(colorF.r, colorF.g, colorF.b, colorF.a);
    }

    internal static SDL.Keycode ToSDL(this Key key) {
        return key switch {
            Key.Null => SDL.Keycode.Unknown,
            Key.Back => SDL.Keycode.AcBack,
            Key.VolumeUp => SDL.Keycode.VolumeUp,
            Key.VolumeDown => SDL.Keycode.VolumeDown,
            Key.Space => SDL.Keycode.Space,
            Key.Apostrophe => SDL.Keycode.Apostrophe,
            Key.Comma => SDL.Keycode.Comma,
            Key.Minus => SDL.Keycode.Minus,
            Key.Period => SDL.Keycode.Period,
            Key.Slash => SDL.Keycode.Slash,
            Key.Digit0 => SDL.Keycode.Alpha0,
            Key.Digit1 => SDL.Keycode.Alpha1,
            Key.Digit2 => SDL.Keycode.Alpha2,
            Key.Digit3 => SDL.Keycode.Alpha3,
            Key.Digit4 => SDL.Keycode.Alpha4,
            Key.Digit5 => SDL.Keycode.Alpha5,
            Key.Digit6 => SDL.Keycode.Alpha6,
            Key.Digit7 => SDL.Keycode.Alpha7,
            Key.Digit8 => SDL.Keycode.Alpha8,
            Key.Digit9 => SDL.Keycode.Alpha9,
            Key.Semicolon => SDL.Keycode.Semicolon,
            Key.Equal => SDL.Keycode.Equals,
            Key.A => SDL.Keycode.A,
            Key.B => SDL.Keycode.B,
            Key.C => SDL.Keycode.C,
            Key.D => SDL.Keycode.D,
            Key.E => SDL.Keycode.E,
            Key.F => SDL.Keycode.F,
            Key.G => SDL.Keycode.G,
            Key.H => SDL.Keycode.H,
            Key.I => SDL.Keycode.I,
            Key.J => SDL.Keycode.J,
            Key.K => SDL.Keycode.K,
            Key.L => SDL.Keycode.L,
            Key.M => SDL.Keycode.M,
            Key.N => SDL.Keycode.N,
            Key.O => SDL.Keycode.O,
            Key.P => SDL.Keycode.P,
            Key.Q => SDL.Keycode.Q,
            Key.R => SDL.Keycode.R,
            Key.S => SDL.Keycode.S,
            Key.T => SDL.Keycode.T,
            Key.U => SDL.Keycode.U,
            Key.V => SDL.Keycode.V,
            Key.W => SDL.Keycode.W,
            Key.X => SDL.Keycode.X,
            Key.Y => SDL.Keycode.Y,
            Key.Z => SDL.Keycode.Z,
            Key.LeftBracket => SDL.Keycode.LeftBracket,
            Key.Backslash => SDL.Keycode.Backslash,
            Key.RightBracket => SDL.Keycode.RightBracket,
            Key.Grave => SDL.Keycode.Grave,
            Key.Escape => SDL.Keycode.Escape,
            Key.Enter => SDL.Keycode.Return,
            Key.Tab => SDL.Keycode.Tab,
            Key.Backspace => SDL.Keycode.Backspace,
            Key.Insert => SDL.Keycode.Insert,
            Key.Delete => SDL.Keycode.Delete,
            Key.Right => SDL.Keycode.Right,
            Key.Left => SDL.Keycode.Left,
            Key.Down => SDL.Keycode.Down,
            Key.Up => SDL.Keycode.Up,
            Key.PageUp => SDL.Keycode.Pageup,
            Key.PageDown => SDL.Keycode.Pagedown,
            Key.Home => SDL.Keycode.Home,
            Key.End => SDL.Keycode.End,
            Key.CapsLock => SDL.Keycode.Capslock,
            Key.ScrollLock => SDL.Keycode.ScrollLock,
            Key.NumLock => SDL.Keycode.NumLockClear,
            Key.PrintScreen => SDL.Keycode.PrintScreen,
            Key.Pause => SDL.Keycode.Pause,
            Key.F1 => SDL.Keycode.F1,
            Key.F2 => SDL.Keycode.F2,
            Key.F3 => SDL.Keycode.F3,
            Key.F4 => SDL.Keycode.F4,
            Key.F5 => SDL.Keycode.F5,
            Key.F6 => SDL.Keycode.F6,
            Key.F7 => SDL.Keycode.F7,
            Key.F8 => SDL.Keycode.F8,
            Key.F9 => SDL.Keycode.F9,
            Key.F10 => SDL.Keycode.F10,
            Key.F11 => SDL.Keycode.F11,
            Key.F12 => SDL.Keycode.F12,
            Key.Keypad0 => SDL.Keycode.Kp0,
            Key.Keypad1 => SDL.Keycode.Kp1,
            Key.Keypad2 => SDL.Keycode.Kp2,
            Key.Keypad3 => SDL.Keycode.Kp3,
            Key.Keypad4 => SDL.Keycode.Kp4,
            Key.Keypad5 => SDL.Keycode.Kp5,
            Key.Keypad6 => SDL.Keycode.Kp6,
            Key.Keypad7 => SDL.Keycode.Kp7,
            Key.Keypad8 => SDL.Keycode.Kp8,
            Key.Keypad9 => SDL.Keycode.Kp9,
            Key.KeypadPeriod => SDL.Keycode.KpPeriod,
            Key.KeypadSlash => SDL.Keycode.KpDivide,
            Key.KeypadMultiply => SDL.Keycode.KpMultiply,
            Key.KeypadMinus => SDL.Keycode.KpMinus,
            Key.KeypadPlus => SDL.Keycode.KpPlus,
            Key.KeypadEnter => SDL.Keycode.KpEnter,
            Key.KeypadEqual => SDL.Keycode.KpEquals,
            Key.LeftShift => SDL.Keycode.LShift,
            Key.LeftControl => SDL.Keycode.LCtrl,
            Key.LeftAlt => SDL.Keycode.LAlt,
            Key.LeftSuper => SDL.Keycode.LGUI,
            Key.RightShift => SDL.Keycode.RShift,
            Key.RightControl => SDL.Keycode.RCtrl,
            Key.RightAlt => SDL.Keycode.RAlt,
            Key.RightSuper => SDL.Keycode.RGUI,
            Key.Menu => SDL.Keycode.Menu,
            _ => throw new ArgumentOutOfRangeException(nameof(key), key, null)
        };
    }

    internal static Key ToRayBlast(this SDL.Keycode key) {
        return key switch {
            SDL.Keycode.Unknown => Key.Null,
            SDL.Keycode.AcBack => Key.Back,
            SDL.Keycode.VolumeUp => Key.VolumeUp,
            SDL.Keycode.VolumeDown => Key.VolumeDown,
            SDL.Keycode.Space => Key.Space,
            SDL.Keycode.Apostrophe => Key.Apostrophe,
            SDL.Keycode.Comma => Key.Comma,
            SDL.Keycode.Minus => Key.Minus,
            SDL.Keycode.Period => Key.Period,
            SDL.Keycode.Slash => Key.Slash,
            SDL.Keycode.Alpha0 => Key.Digit0,
            SDL.Keycode.Alpha1 => Key.Digit1,
            SDL.Keycode.Alpha2 => Key.Digit2,
            SDL.Keycode.Alpha3 => Key.Digit3,
            SDL.Keycode.Alpha4 => Key.Digit4,
            SDL.Keycode.Alpha5 => Key.Digit5,
            SDL.Keycode.Alpha6 => Key.Digit6,
            SDL.Keycode.Alpha7 => Key.Digit7,
            SDL.Keycode.Alpha8 => Key.Digit8,
            SDL.Keycode.Alpha9 => Key.Digit9,
            SDL.Keycode.Semicolon => Key.Semicolon,
            SDL.Keycode.Equals => Key.Equal,
            SDL.Keycode.A => Key.A,
            SDL.Keycode.B => Key.B,
            SDL.Keycode.C => Key.C,
            SDL.Keycode.D => Key.D,
            SDL.Keycode.E => Key.E,
            SDL.Keycode.F => Key.F,
            SDL.Keycode.G => Key.G,
            SDL.Keycode.H => Key.H,
            SDL.Keycode.I => Key.I,
            SDL.Keycode.J => Key.J,
            SDL.Keycode.K => Key.K,
            SDL.Keycode.L => Key.L,
            SDL.Keycode.M => Key.M,
            SDL.Keycode.N => Key.N,
            SDL.Keycode.O => Key.O,
            SDL.Keycode.P => Key.P,
            SDL.Keycode.Q => Key.Q,
            SDL.Keycode.R => Key.R,
            SDL.Keycode.S => Key.S,
            SDL.Keycode.T => Key.T,
            SDL.Keycode.U => Key.U,
            SDL.Keycode.V => Key.V,
            SDL.Keycode.W => Key.W,
            SDL.Keycode.X => Key.X,
            SDL.Keycode.Y => Key.Y,
            SDL.Keycode.Z => Key.Z,
            SDL.Keycode.LeftBracket => Key.LeftBracket,
            SDL.Keycode.Backslash => Key.Backslash,
            SDL.Keycode.RightBracket => Key.RightBracket,
            SDL.Keycode.Grave => Key.Grave,
            SDL.Keycode.Escape => Key.Escape,
            SDL.Keycode.Return => Key.Enter,
            SDL.Keycode.Tab => Key.Tab,
            SDL.Keycode.Backspace => Key.Backspace,
            SDL.Keycode.Insert => Key.Insert,
            SDL.Keycode.Delete => Key.Delete,
            SDL.Keycode.Right => Key.Right,
            SDL.Keycode.Left => Key.Left,
            SDL.Keycode.Down => Key.Down,
            SDL.Keycode.Up => Key.Up,
            SDL.Keycode.Pageup => Key.PageUp,
            SDL.Keycode.Pagedown => Key.PageDown,
            SDL.Keycode.Home => Key.Home,
            SDL.Keycode.End => Key.End,
            SDL.Keycode.Capslock => Key.CapsLock,
            SDL.Keycode.ScrollLock => Key.ScrollLock,
            SDL.Keycode.NumLockClear => Key.NumLock,
            SDL.Keycode.PrintScreen => Key.PrintScreen,
            SDL.Keycode.Pause => Key.Pause,
            SDL.Keycode.F1 => Key.F1,
            SDL.Keycode.F2 => Key.F2,
            SDL.Keycode.F3 => Key.F3,
            SDL.Keycode.F4 => Key.F4,
            SDL.Keycode.F5 => Key.F5,
            SDL.Keycode.F6 => Key.F6,
            SDL.Keycode.F7 => Key.F7,
            SDL.Keycode.F8 => Key.F8,
            SDL.Keycode.F9 => Key.F9,
            SDL.Keycode.F10 => Key.F10,
            SDL.Keycode.F11 => Key.F11,
            SDL.Keycode.F12 => Key.F12,
            SDL.Keycode.Kp0 => Key.Keypad0,
            SDL.Keycode.Kp1 => Key.Keypad1,
            SDL.Keycode.Kp2 => Key.Keypad2,
            SDL.Keycode.Kp3 => Key.Keypad3,
            SDL.Keycode.Kp4 => Key.Keypad4,
            SDL.Keycode.Kp5 => Key.Keypad5,
            SDL.Keycode.Kp6 => Key.Keypad6,
            SDL.Keycode.Kp7 => Key.Keypad7,
            SDL.Keycode.Kp8 => Key.Keypad8,
            SDL.Keycode.Kp9 => Key.Keypad9,
            SDL.Keycode.KpPeriod => Key.KeypadPeriod,
            SDL.Keycode.KpDivide => Key.KeypadSlash,
            SDL.Keycode.KpMultiply => Key.KeypadMultiply,
            SDL.Keycode.KpMinus => Key.KeypadMinus,
            SDL.Keycode.KpPlus => Key.KeypadPlus,
            SDL.Keycode.KpEnter => Key.KeypadEnter,
            SDL.Keycode.KpEquals => Key.KeypadEqual,
            SDL.Keycode.LShift => Key.LeftShift,
            SDL.Keycode.LCtrl => Key.LeftControl,
            SDL.Keycode.LAlt => Key.LeftAlt,
            SDL.Keycode.LGUI => Key.LeftSuper,
            SDL.Keycode.RShift => Key.RightShift,
            SDL.Keycode.RCtrl => Key.RightControl,
            SDL.Keycode.RAlt => Key.RightAlt,
            SDL.Keycode.RGUI => Key.RightSuper,
            SDL.Keycode.Menu => Key.Menu,
            _ => throw new ArgumentOutOfRangeException(nameof(key), key, null)
        };
    }

    internal static SDL.GamepadAxis ToSDL(this GamepadAxis axis) {
        return axis switch {
            GamepadAxis.Null => SDL.GamepadAxis.Invalid,
            GamepadAxis.LeftX => SDL.GamepadAxis.LeftX,
            GamepadAxis.LeftY => SDL.GamepadAxis.LeftY,
            GamepadAxis.RightX => SDL.GamepadAxis.RightX,
            GamepadAxis.RightY => SDL.GamepadAxis.RightY,
            GamepadAxis.LeftTrigger => SDL.GamepadAxis.LeftTrigger,
            GamepadAxis.RightTrigger => SDL.GamepadAxis.RightTrigger,
            _ => throw new ArgumentOutOfRangeException(nameof(axis), axis, null)
        };
    }

    internal static GamepadAxis ToRayBlast(this SDL.GamepadAxis axis) {
        return axis switch {
            SDL.GamepadAxis.Invalid => GamepadAxis.Null,
            SDL.GamepadAxis.LeftX => GamepadAxis.LeftX,
            SDL.GamepadAxis.LeftY => GamepadAxis.LeftY,
            SDL.GamepadAxis.RightX => GamepadAxis.RightX,
            SDL.GamepadAxis.RightY => GamepadAxis.RightY,
            SDL.GamepadAxis.LeftTrigger => GamepadAxis.LeftTrigger,
            SDL.GamepadAxis.RightTrigger => GamepadAxis.RightTrigger,
            SDL.GamepadAxis.Count => throw new ArgumentOutOfRangeException(nameof(axis), axis, null),
            _ => throw new ArgumentOutOfRangeException(nameof(axis), axis, null)
        };
    }

    internal static SDL.GamepadButton ToSDL(this GamepadButton button) {
        return button switch {
            GamepadButton.Null => SDL.GamepadButton.Invalid,
            GamepadButton.South => SDL.GamepadButton.South,
            GamepadButton.East => SDL.GamepadButton.East,
            GamepadButton.West => SDL.GamepadButton.West,
            GamepadButton.North => SDL.GamepadButton.North,
            GamepadButton.LeftShoulder => SDL.GamepadButton.LeftShoulder,
            GamepadButton.RightShoulder => SDL.GamepadButton.RightShoulder,
            GamepadButton.Start => SDL.GamepadButton.Start,
            GamepadButton.Select => SDL.GamepadButton.Back,
            GamepadButton.LeftStick => SDL.GamepadButton.LeftStick,
            GamepadButton.RightStick => SDL.GamepadButton.RightStick,
            GamepadButton.DPadUp => SDL.GamepadButton.DPadUp,
            GamepadButton.DPadDown => SDL.GamepadButton.DPadDown,
            GamepadButton.DPadLeft => SDL.GamepadButton.DPadLeft,
            GamepadButton.DPadRight => SDL.GamepadButton.DPadRight,
            GamepadButton.Guide => SDL.GamepadButton.Guide,
            GamepadButton.Touchpad => SDL.GamepadButton.Touchpad,
            GamepadButton.LeftPaddle1 => SDL.GamepadButton.LeftPaddle1,
            GamepadButton.RightPaddle1 => SDL.GamepadButton.RightPaddle1,
            GamepadButton.LeftPaddle2 => SDL.GamepadButton.LeftPaddle2,
            GamepadButton.RightPaddle2 => SDL.GamepadButton.RightPaddle2,
            GamepadButton.Misc1 => SDL.GamepadButton.Misc1,
            GamepadButton.Misc2 => SDL.GamepadButton.Misc2,
            GamepadButton.Misc3 => SDL.GamepadButton.Misc3,
            GamepadButton.Misc4 => SDL.GamepadButton.Misc4,
            GamepadButton.Misc5 => SDL.GamepadButton.Misc5,
            GamepadButton.Misc6 => SDL.GamepadButton.Misc6,
            _ => throw new ArgumentOutOfRangeException(nameof(button), button, null)
        };
    }

    internal static GamepadButton ToRayBlast(this SDL.GamepadButton button) {
        return button switch {
            SDL.GamepadButton.Invalid => GamepadButton.Null,
            SDL.GamepadButton.South => GamepadButton.South,
            SDL.GamepadButton.East => GamepadButton.East,
            SDL.GamepadButton.West => GamepadButton.West,
            SDL.GamepadButton.North => GamepadButton.North,
            SDL.GamepadButton.LeftShoulder => GamepadButton.LeftShoulder,
            SDL.GamepadButton.RightShoulder => GamepadButton.RightShoulder,
            SDL.GamepadButton.Start => GamepadButton.Start,
            SDL.GamepadButton.Back => GamepadButton.Select,
            SDL.GamepadButton.LeftStick => GamepadButton.LeftStick,
            SDL.GamepadButton.RightStick => GamepadButton.RightStick,
            SDL.GamepadButton.DPadUp => GamepadButton.DPadUp,
            SDL.GamepadButton.DPadDown => GamepadButton.DPadDown,
            SDL.GamepadButton.DPadLeft => GamepadButton.DPadLeft,
            SDL.GamepadButton.DPadRight => GamepadButton.DPadRight,
            SDL.GamepadButton.Guide => GamepadButton.Guide,
            SDL.GamepadButton.Touchpad => GamepadButton.Touchpad,
            SDL.GamepadButton.LeftPaddle1 => GamepadButton.LeftPaddle1,
            SDL.GamepadButton.RightPaddle1 => GamepadButton.RightPaddle1,
            SDL.GamepadButton.LeftPaddle2 => GamepadButton.LeftPaddle2,
            SDL.GamepadButton.RightPaddle2 => GamepadButton.RightPaddle2,
            SDL.GamepadButton.Misc1 => GamepadButton.Misc1,
            SDL.GamepadButton.Misc2 => GamepadButton.Misc2,
            SDL.GamepadButton.Misc3 => GamepadButton.Misc3,
            SDL.GamepadButton.Misc4 => GamepadButton.Misc4,
            SDL.GamepadButton.Misc5 => GamepadButton.Misc5,
            SDL.GamepadButton.Misc6 => GamepadButton.Misc6,
            SDL.GamepadButton.Count => throw new ArgumentOutOfRangeException(nameof(button), button, null),
            _ => throw new ArgumentOutOfRangeException(nameof(button), button, null)
        };
    }

    internal static SDL.JoystickHat ToSDL(this HatState hat) {
        return (SDL.JoystickHat)hat;
    }

    internal static HatState ToRayBlast(this SDL.JoystickHat hat) {
        return (HatState)hat;
    }
}
